---
# file:roles/redis-metrics/tasks/main.yml
#
- name: Copy redis-metrics to remote machine
  copy: src=redis-metrics.tar.gz dest={{ opbin_dir}} mode=644
  ignore_errors: no

- name: Install redis-metrics
  shell: "su -l {{ deploy_user }} -c ' [ -d {{ opbin_dir }}/redis-metrics ] || ( cd {{ opbin_dir }} && tar -zxf redis-metrics.tar.gz && rm -rf redis-metrics.tar.gz ) '"
  ignore_errors: yes

- name: Setup falcon transfer url
  copy: src=cfg.json.redis dest={{ opbin_dir }}/{{ module }}/cfg.json mode=644

- name: Start program for {{ module }} .
  shell: chdir=/opt {{ item }}
  with_items:
    - "{{ opbin_dir }}/{{ module }}/control restart"
  ignore_errors: no
